### ISSUE TITLE
When printing to a device without color, print the content without color, but no additional content

### ISSUE THREAD

**Issue by sbellware** [test-bench/test-bench#5]

**Comment by ntl** [comment]
This is largely done, with one exception. When tests are skipped, and color is on, their text is printed in yellow. Otherwise, their output is no different than tests that pass. Therefore, I think it's appropriate to append `(skipped)` to skipped tests. So, given the following test code:

```ruby
context "Some Context" do
  test "Some test" do
    assert(true)
  end
  test "Other test"
end
```

The output would look like this:

```
Some Context
  Some test
  Other test (skipped)
end
```
